DEBUG: True
CONDITIONS:
  - WT
  - CTRL
  - DTR
  - CNO

STRAINS:
  - C57
  - VGLUT

STANDING_STILL: False  # set to true when processing standing still trials

# ----------------------- sensors data pre-processsing ----------------------- #
calibrate: True  # !!! currently all code assumes this to be TRUE, dont change
weight_percentage: True  # !!! currently all code assumes this to be TRUE, dont change
correct_for_paw: True  #  adjust all data to make it look like mice always step with the R paw


# ----------------------------------- paths ---------------------------------- #
frames_file: "F:\\Egzona\\Forceplate\\240522_ALL_trials_2022_analysis.csv"  # CSV with trials start frames and metadata
calibration_file: "F:\\Egzona\\Forceplate\\forceplatesensors_calibration4.csv"  # CSV with volts/gr calibration data
main_fld: "F:\\Egzona\\Forceplate\\CURRENT ANALYSIS TRIALS"  # main data folder.

# --------------------------------- analysis --------------------------------- #
fps: 600  # all trials are scaled in time to have this target FPS

smoothing_window: 0.01  # in seconds - width of smoothing gaussian kernel
on_sensor_weight_th: 2  # in % of mouse body weight: when > th weight the mouse is 'on' the sensor
on_all_sensors_weight_th: 66  # in % of body weight: when > th weight across all sensors the mouse is on sensors

n_secs_before: 0.2  # number of seconds before start of trial to keep for plotting etc
n_secs_after: 0.2  # number of seconds after start of trial to keep for plotting etc

min_baseline_duration: 0  # in seconds | min duration of baseline to keep mouse
trial_start_detection_window: 0.15  # in seconds | trial start is the first frame in which FR moves in a small winodw around Egzona's trial start frame

# --------------------------------- plotting --------------------------------- #
plot_individual_trials: False